/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import models.GameBoard;
import models.Phase;
import resources.Constants;

/**
 * This class contains the View of the Phase
 *
 * @author daksh
 */
public class PhaseView extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form PhaseView
     */
    public PhaseView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLableCurrentPhase = new javax.swing.JLabel();
        jLabelPlayerName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        actionList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLableCurrentPhase.setText("jLabel1");

        jLabelPlayerName.setText("jLabel2");

        actionList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(actionList);

        jLabel1.setText("Actions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLableCurrentPhase)
                        .addGap(93, 93, 93)
                        .addComponent(jLabelPlayerName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLableCurrentPhase)
                    .addComponent(jLabelPlayerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Shows the view of Phase
     */
    public void showView() {
        jLableCurrentPhase.setText(Constants.STARTUP_PHASE);
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList actionList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPlayerName;
    private javax.swing.JLabel jLableCurrentPhase;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    /**
     * Update method of the Phase View
     *
     * @param o Observable object
     * @param arg Object of observable i.e Phase
     */
    @Override
    public void update(Observable o, Object arg) {
        GameBoard gameBoard = (GameBoard) o;
        Phase currentPhase = gameBoard.getCurrentPhaseDetails();
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                updateView(currentPhase);
            }
        });

    }

    /**
     * Updates the View of the Phase
     *
     * @param currentPhase Object of the current Phase {@link models.Phase}
     */
    private void updateView(Phase currentPhase) {
        String phaseName = currentPhase.getPhaseName();
        String playerName = currentPhase.getPlayerName();
        List actions = currentPhase.getActions();

        jLableCurrentPhase.setText(phaseName);
        jLabelPlayerName.setText(playerName);

        DefaultListModel lm = new DefaultListModel();
        for (int i = 0; i < actions.size(); i++) {
            lm.addElement(actions.get(i));
        }
        actionList.setModel(lm);
    }

}
